export const initialState = {
    isOpened: undefined,
    reopen: false,
    data: [],
    invalidData: true,
    isLoading: true,
    unsavedChanges: false,
    maxHeight: 0,
    maxWidth: 0,
    minWidth: 0,
    buttonWidth: undefined,
    inputValue: '',
    itemWidth: null,
    itemHeight: null,
    checkedItemsValue: [],
    checkedItemsLabel: [],
    checkedItemsCounter: 0,
}